title:            Sasha Vinčić
description:      My notes about work, security and internet of things. 
logo:             site-logo.png
disqus_shortname: vincic
#Comment out url when working locally to resolve base urls correctly
url:              https://sasha.vincic.org

# Owner/author information
owner:
  name:           Sasha Vincic
  avatar:         http://www.gravatar.com/avatar/c98818113e6d383bde6dbcc463681414.png
  email:          sasha@vincic.org
  # Social networking links used in footer. Update and remove as you like.
  twitter:        vincic
  facebook:       sashavincic
  github:         vincic
  linkedin:       sashav
  instagram:      vincic
  flickr:         sashav
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    //plus.google.com/110531523203599907630

# Analytics and webmaster tools stuff goes here
google_analytics: UA-1635911-2
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Blog
    url: /blog/
  - title: About
    url: /about/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Stockholm
future:      true
highlighter:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "so-simple-theme.sublime-project", "so-simple-theme.sublime-workspace"]